# Generated by Django 4.1.3 on 2022-12-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_pie_bread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='related_carts', to='catalog.cartproduct'),
        ),
    ]
